## 배열 전치와 축 변경
- 전치행렬
- arr.T      # T는 전치를 의미함
- arr.transpose()

In [1]:
import numpy as np
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [3]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### 표준 정규 분포
- standard normal distribution
- 데이터의 평균 : 0 
- 표준편차 : 1 
- np.random.randn()

In [5]:
# 전치행렬의 사용 예
arr = np.random.randn(6,3)  # n = normal distribution (정규분포)
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [7]:
arr.min(),arr.mean(),arr.max()

(-0.7128905937269998, 0.15457857965610844, 1.762614671116347)

In [9]:
arr_1 = np.random.random(18)
arr_1.min(), arr_1.mean(), arr_1.max()  # 정규분포가 아님 

(0.07389872560093158, 0.48160338356763543, 0.9734951287258605)

In [ ]:
# 벡터의 내적 연산(Dot Product) A,B 
np.dot(arr.T,arr)  # dot = 내적

### 유니버설 함수
- ndarray 안에 있는 데이터 원소별로 각각 연산을 수행하는 numpy 함수
- 레퍼런스:

In [10]:
import numpy as np

In [12]:
np.array([1,2,3]) * 2    # ndarray와 스칼라 수의 곱셈(함수가 아닌 경우)

array([2, 4, 6])

In [15]:
arr = np.arange(10)

In [17]:
arr_1 = np.sqrt(arr)
print(arr_1)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [18]:
np.exp(arr)  
# 자연상수(E) : 2.7182818283....

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [19]:
x = np.random.randn(8)
y = np.random.randn(8)

In [20]:
x,y

(array([ 1.05614126,  1.66727272, -0.64763576, -1.0775132 ,  1.40547455,
         1.04548546, -0.07007643,  0.78131915]),
 array([ 0.15266152, -0.46204762,  0.08368293,  0.24690381, -0.53536388,
        -0.6826272 , -1.65773938,  0.58237255]))

In [22]:
np.maximum(x,y)

array([ 1.05614126,  1.66727272,  0.08368293,  0.24690381,  1.40547455,
        1.04548546, -0.07007643,  0.78131915])

In [24]:
# x,y 2개의 배열에 들어 있는 데이터를 각 동일위치의 데이터와 합산
import numpy as np

x = np.random.randn(8)
y = np.random.randn(8)

result = np.add(x, y)

print("x 배열:", x)
print("y 배열:", y)
print("합산 결과:", result)


x 배열: [ 0.34190888  0.54690193 -0.77230166 -0.02135352 -0.7229947  -0.32647581
  0.08039991 -0.54251358]
y 배열: [-0.10394689 -0.06225815  1.85094251 -0.34640834  0.96482449 -0.88819507
 -2.33919756 -1.61657949]
합산 결과: [ 0.23796199  0.48464379  1.07864085 -0.36776186  0.24182979 -1.21467088
 -2.25879765 -2.15909307]


In [27]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

### ndarray 함수 vs 일반 반복문을 이용한 계산 속도 비교

In [28]:
import numpy as np

In [29]:
points = np.arange(10000000,dtype='f')
points[:10]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [30]:
%%time
total = 0
for i in points:
    total += i
print(total)

49999995000000.0
CPU times: total: 2.52 s
Wall time: 2.52 s


In [31]:
%time points.sum()

CPU times: total: 15.6 ms
Wall time: 10.1 ms


50000000000000.0

In [39]:
zipObj = zip([1,2,3],['a','b','c'],['가','나','다'])
print(zipObj)

In [40]:
#dir(zipObj)
for v in zipObj:
    print(v)

(1, 'a', '가')
(2, 'b', '나')
(3, 'c', '다')


In [41]:
list(zipObj)   # 위에서 Generator의 값을 소진했기 때문에 여기서는 없다

[]

In [51]:
def sample_gen():
    yield 'a'
    yield 'b'
    yield 'c'

In [53]:
gen1 = sample_gen()

In [60]:
def num_gen():
    for v in range(1,6):
        yield v

In [61]:
for v in num_gen():
    print(v,end=" ")

1 2 3 4 5 

In [57]:
list(gen2)

['1', '2', '3', '4', '5']

In [52]:
list(gen1)

[]

In [71]:
# Generator Comprehension
gen2 = ( v for v in range(1,6) )
print(gen2)

<generator object <genexpr> at 0x000001ECE40C36B0>


In [72]:
for v in gen2:
    print(v,end=" ")

1 2 3 4 5 

In [54]:
for v in gen1:
    print(v, end=",")

a,b,c,

In [73]:
# Generator 에 대해 루프를 사용하지 않고 값을 한개씩 추출하기
gen = num_gen()
print(next(gen))
print(next(gen))

1
2


In [76]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

In [77]:
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [78]:
result = np.where(cond,xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
### Generator를 이용하여 텍스트 파일에서 한행씩 가져오는 예
- 파일명 : members.txt
- member(num,name,phone)
- 한행씩 Generator를 이용하여 가져와서 화면에 목록으로 표시하기

In [80]:
class Member:
    def __init__(self, num, name, phone):
        self.num = num
        self.name = name
        self.phone = phone

def read_members_file(filename):
    with open(filename, 'r') as file:
        for line in file:
            num, name, phone = line.strip().split(',')
            yield Member(num, name, phone)

# members.txt 파일로부터 한 줄씩 Member 객체를 생성하는 제네레이터를 생성합니다.
members_generator = read_members_file('D:/test/members.txt')

# 제네레이터를 이용하여 파일의 내용을 한 줄씩 처리합니다.
for member in members_generator:
    print("Member:", member.num, member.name, member.phone)


Member: 1 Lee 010-1111-2222
Member: 2 Park 010-2222-3333
Member: 3 Choi 010-3333-4444


In [84]:
arr = np.random.randn(4,4)
arr

array([[ 0.34993288, -0.6046164 , -1.64591933,  0.25418968],
       [ 2.00449785, -0.29842461, -0.15946016,  0.16736783],
       [-0.53871771, -0.17961968, -0.98890566, -1.39072741],
       [ 1.06509445, -1.20134817, -0.93180735,  0.95982319]])

In [85]:
arr>0

array([[ True, False, False,  True],
       [ True, False, False,  True],
       [False, False, False, False],
       [ True, False, False,  True]])

In [86]:
np.where(arr>0,2,-2)

array([[ 2, -2, -2,  2],
       [ 2, -2, -2,  2],
       [-2, -2, -2, -2],
       [ 2, -2, -2,  2]])

In [87]:
np.where(arr>0,2,arr)

array([[ 2.        , -0.6046164 , -1.64591933,  2.        ],
       [ 2.        , -0.29842461, -0.15946016,  2.        ],
       [-0.53871771, -0.17961968, -0.98890566, -1.39072741],
       [ 2.        , -1.20134817, -0.93180735,  2.        ]])

### 수학 메소드와 통계

In [88]:
arr = np.random.randn(5,4)
arr

array([[ 0.00464633, -1.76214696, -0.04497371, -1.39632584],
       [ 0.76328093,  0.23818382,  0.28605323,  0.83749686],
       [ 0.13932562,  2.36507945, -0.48493169, -0.9117908 ],
       [-0.93800415,  1.28608371, -1.14298721, -0.47682086],
       [ 0.235008  , -0.17853078, -0.64604027, -0.66706309]])

In [89]:
arr.mean(),np.mean(arr)

(-0.12472287067824184, -0.12472287067824184)

In [91]:
arr.sum() , np.sum(arr)

(-2.4944574135648367, -2.4944574135648367)

## 연산 축(axis)방향
- 행방향(행끼리의 계산) : 0, 세로 연산
- 열방향(열끼리의 계산) : 1, 가로 연산

In [92]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
arr.sum()  # 36, 원소 전체의 합

36

In [94]:
arr.sum(axis=0)  # 행들의 합(행끼리의 합), 세로 합 

array([ 9, 12, 15])

In [95]:
arr.sum(0)

array([ 9, 12, 15])

In [96]:
arr.sum(axis=1) # 열들의 합(열끼리의 합), 가로 합

array([ 3, 12, 21])

In [97]:
arr.mean(axis=1) # 열들의 평균, 가로 평균

array([1., 4., 7.])

## 누적연산
- arr.cumsum():누적 합산마다 산출되는 값 배열 리턴
- arr.cumprod():누적 곱 과정마다 산출되는 값 배열 리턴

In [98]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
arr.cumsum()  # 전체에 대한 누적 합 과정의 산출 값 배열

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [100]:
arr.cumsum(axis=0)  # 행들의 누적 합, 세로 누적 합

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [101]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [102]:
arr.cumprod() # 전체 누적 곱

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [103]:
arr.cumprod(axis=0)  # 누적 곱 과정 배열

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

In [104]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

## 통계 메소드
- var : sum ((arr-m) ^2) / N
- std : sqrt(var)

In [106]:
np.random.seed(0)

In [110]:
# 분산 구하기(수동으로 구하기)
arr = np.arange(5)

In [108]:
import numpy as np

arr = np.arange(5)

# 평균 계산
m = np.mean(arr)

# 분산 계산
squared_diff = (arr - m)**2
var = np.sum(squared_diff) / len(arr)

# 표준편차 계산
std = np.sqrt(var)

print("분산:", var)
print("표준편차:", std)


분산: 2.0
표준편차: 1.4142135623730951


In [112]:
arr = np.arange(5)

m = np.mean(arr)

a = (arr-m)**2
var = np.sum(a) / len(arr)

std = np.sqrt(var)

print("분산:",var)
print("표준편차:",std)

분산: 2.0
표준편차: 1.4142135623730951


In [105]:
arr = np.random.randn(100)

In [114]:
max_idx = arr.argmax()
arr[max_idx]   # 4 

4

In [116]:
min_idx = arr.argmin()
arr[min_idx]   # 0 

0

In [118]:
# 무작위 실수 10개를 추출하여 그 중 최소/최대값의 인덱스를 구해보세요
np.random.seed(0)

In [122]:
import numpy as np

# 시드 설정
np.random.seed(0)

# 무작위 실수 10개 추출
random_numbers = np.random.rand(10)

# 최소값과 최대값의 인덱스 구하기
min_index = np.argmin(random_numbers)
max_index = np.argmax(random_numbers)

print("무작위 실수 배열:", random_numbers)
print("최소값 인덱스:", min_index)
print("최대값 인덱스:", max_index)

무작위 실수 배열: [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
최소값 인덱스: 9
최대값 인덱스: 8


In [123]:
arr = np.random.randn(100)

In [125]:
(arr > 0).sum()   # 0보다 큰 수의 갯수

53

### 정렬
- np.sort(arr) : 원본을 변경하지 않고 정렬된 사본을 리턴함
- arr.sort() : 원본을 변경하고 값을 리턴하지 않음

In [129]:
import numpy as np

# 원본 배열 생성
arr = np.array([2,5,3,6,4])

# np.sort(arr)를 사용하여 정렬된 사본 생성 (원본 변경 없음)
sorted_copy = np.sort(arr)

# arr.sort()를 사용하여 원본 배열 정렬 (원본이 변경됨)
arr.sort()

# 결과 출력
print("원본 배열:", arr)
print("정렬된 사본:", sorted_copy)

원본 배열: [2 3 4 5 6]
정렬된 사본: [2 3 4 5 6]


In [132]:
arr = np.random.random(16).reshape((4,4))
arr

array([[0.57432525, 0.65320082, 0.65210327, 0.43141844],
       [0.8965466 , 0.36756187, 0.43586493, 0.89192336],
       [0.80619399, 0.70388858, 0.10022689, 0.91948261],
       [0.7142413 , 0.99884701, 0.1494483 , 0.86812606]])

In [133]:
arr_horizontal_sorted = np.sort(arr, axis=1)  # 가로 정렬
print("가로 정렬:")
print(arr_horizontal_sorted)


가로 정렬:
[[0.43141844 0.57432525 0.65210327 0.65320082]
 [0.36756187 0.43586493 0.89192336 0.8965466 ]
 [0.10022689 0.70388858 0.80619399 0.91948261]
 [0.1494483  0.7142413  0.86812606 0.99884701]]


In [136]:
arr_vertical_sorted = np.sort(arr, axis=0)
print("세로 정렬:")
print(arr_vertical_sorted)

세로 정렬:
[[0.57432525 0.36756187 0.10022689 0.43141844]
 [0.7142413  0.65320082 0.1494483  0.86812606]
 [0.80619399 0.70388858 0.43586493 0.89192336]
 [0.8965466  0.99884701 0.65210327 0.91948261]]


In [ ]:
# 교집합 : intersect1d(x,y)
# 합집합 : union1d(x,y)
# in1d(x,y) : y가 x의 멤버인가? 
# 차집합 : setdiff1d(x,y)
# 대칭차집합 : setxor1d(x,y), 한집합에는 포함되나, 두 집합 모두에는 없는 원소

In [138]:
import numpy as np

# 두 배열 생성
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([4, 5, 6, 7, 8, 9])

# 교집합
intersection = np.intersect1d(x, y)
print("교집합:", intersection)

# 합집합
union = np.union1d(x, y)
print("합집합:", union)

# y가 x의 멤버인가?
membership = np.in1d(x, y)
print("y가 x의 멤버인가?", membership)

# 차집합
difference = np.setdiff1d(x, y)
print("차집합:", difference)

# 대칭 차집합 -> 합집합에서 교집합 성분을 뺀 것 
symmetric_difference = np.setxor1d(x, y)
print("대칭 차집합:", symmetric_difference)


교집합: [4 5 6]
합집합: [1 2 3 4 5 6 7 8 9]
x가 y의 멤버인가? [False False False  True  True  True]
차집합: [1 2 3]
대칭 차집합: [1 2 3 7 8 9]
